### ISSUE TITLE
[Bug]: 413 Request Entity Too Large

### ISSUE THREAD

**Issue by NaniNorris** [comet-ml/opik#834]
### What component(s) are affected?

- [X] Python SDK
- [ ] Opik UI
- [X] Opik Server
- [ ] Documentation

### Opik version

- Opik version: x.x.x

### Describe the problem

While running the Agentic RAG implemented in Langchain Encountered a BUG when the document are too large. Thias returns HTML error as below and not able to trace.

OPIK: Failed to process CreateSpansBatchMessage. Content: CreateSpansBatchMessage(batch=[CreateSpanMessage(span_id='06739c7d-6aee-751c-8000-3ea979eeb8fb', trace_id='06739c7d-6888-7877-8000-c7469bda943d', project_name='phase_4_batch_5', parent_span_id='06739c7d-6ae6-78bd-8000-03652ca1646c', name='ChatOpenAI', start_time=datetime.datetime(2024, 11, 17, 10, 39, 18, 683194, tzinfo=datetime.timezone.utc), end_time=datetime.datetime(2024, 11, 17, 10, 39, 20, 629980, tzinfo=datetime.timezone.utc), input={'prompts': ['System: You are an amazing .............

<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.27.2</center>
</body>
</html>
Traceback (most recent call last):
  File "/home/merit/anaconda3/envs/div/lib/python3.11/site-packages/opik/rest_api/spans/client.py", line 337, in create_spans
    _response_json = _response.json()
                     ^^^^^^^^^^^^^^^^
  File "/home/merit/anaconda3/envs/div/lib/python3.11/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merit/anaconda3/envs/div/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merit/anaconda3/envs/div/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/merit/anaconda3/envs/div/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
...
<hr><center>nginx/1.27.2</center>
</body>
</html>

**Comment by jverre** [comment]
@NaniNorris Oh, that's unexpected we fixed something like this a couple of weeks ago. We'll take a closer look on Monday to try and narrow down the issue 

I'll keep you posted

**Comment by NaniNorris** [comment]
@jverre, May be I might using an older version. Can you help me understand if I down the docker and update the repo and up the docker will the existing data in my project are deleted ? So I can reproduce the above issue at my end

**Comment by jverre** [comment]
@NaniNorris you can update the repo and run the docker compose command again and your data will not be lost.

The data is only lost if you remove the data folders manually

**Comment by azespinoza** [comment]
Can confirm - also experiencing this error on the latest version of Opik (locally hosted, python sdk)

**Comment by jverre** [comment]
@azespinoza Taking another look now, do you have a code snippet so I can reproduce the issue ?

**Comment by azespinoza** [comment]
> @azespinoza Taking another look now, do you have a code snippet so I can reproduce the issue ?

sure! 

```
import opik
opik.configure(use_local=True)
opik_client = opik.Opik()


dataset = opik_client.create_dataset(name="sample dataset")
data = load_data() # returns data, a list of 26 dict records with max(len(input)) == 110281 characters, min(len(input)) == 2000 characters
dataset.insert(data) # 413 error occurs here
```

I have been able to work around the issue by manually copy/pasting each json formatted record into the UI for now, but not ideal

**Comment by NaniNorris** [comment]
@jverre . I have updated to latest version and in tracing langGraph Now the bug is fixed.

**Comment by jverre** [comment]
@azespinoza I looked into it and can't see to reproduce the issue with the example you shared. I did however find a bug in our docs were the upgrade section was missing a command (`docker compose pull`), can you double check if you are running the latest version by following the section here: [https://www.comet.com/docs/opik/self-host/local_deployment#upgrading-opik](https://www.comet.com/docs/opik/self-host/local_deployment#upgrading-opik).

Best way to know if you are running the latest version is that you should have a home page and an updated sidebar like below:

<img width="1536" alt="Screenshot 2024-12-17 at 10 53 37" src="https://github.com/user-attachments/assets/6925b91f-50cc-4436-b9bf-ae8b837b003f" />

**Comment by azespinoza** [comment]
> @azespinoza I looked into it and can't see to reproduce the issue with the example you shared. I did however find a bug in our docs were the upgrade section was missing a command (`docker compose pull`), can you double check if you are running the latest version by following the section here: https://www.comet.com/docs/opik/self-host/local_deployment#upgrading-opik.
> 
> Best way to know if you are running the latest version is that you should have a home page and an updated sidebar like below:
> 
> <img alt="Screenshot 2024-12-17 at 10 53 37" width="1536" src="https://private-user-images.githubusercontent.com/7562001/396468765-6925b91f-50cc-4436-b9bf-ae8b837b003f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODQyMjUsIm5iZiI6MTczNDQ4MzkyNSwicGF0aCI6Ii83NTYyMDAxLzM5NjQ2ODc2NS02OTI1YjkxZi01MGNjLTQ0MzYtYjliZi1hZThiODM3YjAwM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMDEwNTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGJhMDAzNmNjNzgxMjI4ZmMxNjAxMGM2MTBkNzI1NDU5NmNlNzljN2RkNzk5NTQzOGRiZDk2NTc2NGFlYzAwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QMLBJ-jLFw--L4eGw9Ai1NsCO5BsPHDBddUrK84tFJU">

@jverre thanks for the update, the additional command helped me get on the latest version. I still encounter the error when trying to upload the entire dataset using `dataset.insert(data)`.

However, if I modify to insert one (or just a few) item(s) at a time:

```
for record in data:
    dataset.insert([record])
```

then it is successful!

**Comment by jverre** [comment]
@alexkuzmik Any ideas on what might be the issue here ? Didn't we implement "smart" batching for dataset item inserts that works for both cloud and local deployments ?

**Comment by jverre** [comment]
@azespinoza Took a little while be we found the issue, there was a misconfiguration in the docker compose deployments which has now been fixed. If you upgrade to the latest version everything should be working as expected
